version: "3.9"
networks:
  ccp2-network:
    driver: bridge

services:
  redis:
    image: ghcr.io/aut-cloud-computing-fall-2024/redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ccp2-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: k3rn3lpanicc/ccp2-node
    container_name: server
    ports:
      - "3000:3000"
    networks:
      - ccp2-network
    depends_on:
      redis:
        condition: service_healthy
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ccp2-network
    ports:
      - "9090:9090"
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_healthy

volumes:
  redis-data:
