---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ccp2-namespace
spec:
  selector:
    app: app-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ccp2-namespace
spec:
  selector:
    app: redis-service
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
