apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ccp2-namespace
  labels:
    app: app-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - name: app-container
        image: k3rn3lpanicc/ccp2-node:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: project-config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: API_KEY
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
