apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: ccp2-namespace
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi # Define storage size
  accessModes:
    - ReadWriteOnce # Redis only requires single-node access
  persistentVolumeReclaimPolicy: Retain # Keeps data even if the claim is deleted
  storageClassName: redis-storage
  hostPath:
    path: /mnt/data/redis # Path on the host where data is stored (local storage for Minikube)
