apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ccp2-namespace
spec:
  selector:
    app: redis-service
  ports:
    - protocol: TCP
      port: 6379            # Service port
      targetPort: 6379      # Port where Redis listens
  type: LoadBalancer           
