apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ccp2-namespace
spec:
  selector:
    app: app-service
  ports:
    - protocol: TCP
      port: 3000            # Service port
      targetPort: 3000      # Port where the app listens
  type: LoadBalancer          