name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Get Commit Hash
      id: metadata
      run: |
        echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t k3rn3lpanicc/ccp2-node:${GIT_COMMIT} .
        docker tag k3rn3lpanicc/ccp2-node:${GIT_COMMIT} k3rn3lpanicc/ccp2-node:latest

    - name: Push Docker Image
      run: |
        docker push k3rn3lpanicc/ccp2-node:${GIT_COMMIT}
        docker push k3rn3lpanicc/ccp2-node:latest
